# .github/workflows/call-reusable-workflow.yml reusable demo
name: Call Reusable Workflow
on: [push]
jobs:
  call:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      my-input: "Hi Team we executed reusable workflow!"
