name: Day_One_Recap
run-name: ${{ github.actor }} is executing in day 1

on: 
  push: 
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  recapping_day_1:
    runs-on: ubuntu-latest
    environment: Dev
    strategy:
      matrix: 
        names: [Roopa, Shilpa, Vidya]
    steps:
      - name: Running a script
        run: echo "Ran a script in ${{ github.ref }} for persona ${{ matrix.names }}"
      - name: Access repository (using actions)
        uses: actions/checkout@v4
      - name: Checkout local action repository
        uses: actions/checkout@v4
        with:
          repository: sowmya-mvs/Local-action
          path: local-action-repo
      - name: Run Local Action
        uses: ./local-action-repo

  using_reusable_template:
    needs: recapping_day_1
    uses: sowmya-mvs/Local-action/.github/workflows/reusable_workflow.yaml@main
    with:
      param1: 'Hello, world!'
