name: Hello NTTData Team

on: workflow_dispatch

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello NTTData Team-Welcome to GitHubActions Workshop"

      
  



  
