name: Hello NTTData Team

on: 
  push: 
    branches:
      - feature/US15

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello NTTData Team-Welcome to GitHubActions Workshop"

      
  



  
