name: demos
run-name: ${{ github.actor }} is running this Pipeline
on: push

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
    - name: Hello-world
      run: echo "Latest Code push into the main branch"
