name: Day_One_Recap
run-name: ${{ github.actor }} is recapping day one

on: 
  push: 
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  recapping_day_1:
    runs-on: ubuntu-latest
    environment: Prod
    strategy:
      matrix: 
        names: [Vidya,Srinaya]
    steps:
      - name: Running a script
        run: echo "Ran a script in ${{ github.ref }} for persona ${{ matrix.names }} , variable ${{secrets.DAY}}, secret ${{secrets.DATE}}"
      - name: Access repository (using actions)
        uses: actions/checkout@v4
    
